name: Deploy ETL Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no root@137.184.183.44 \
            "mkdir -p /root/etl-pipeline && \
            git -C /root/etl-pipeline pull || git clone https://github.com/Daniishkhan/etl-pipeline.git /root/etl-pipeline && \
            cd /root/etl-pipeline && \
            pip install -r requirements.txt && \
            python3 etl_scripts/main.py"