name: Deploy ETL Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no root@137.184.183.44 \
            "mkdir -p /root/etl-pipeline && \
            # Install Python/pip if missing
            if ! command -v python3 &> /dev/null; then \
              apt update && apt install -y python3 python3-pip python3-venv; \
            fi && \
            # Clone or pull repo
            if [ -d /root/etl-pipeline/.git ]; then \
              git -C /root/etl-pipeline pull origin main; \
            else \
              git clone https://github.com/your-username/etl-pipeline.git /root/etl-pipeline; \
            fi && \
            # Set up virtual environment
            cd /root/etl-pipeline && \
            python3 -m venv venv && \
            . venv/bin/activate && \
            pip install -r requirements.txt && \
            python etl_scripts/main.py"